doc-warnings: no # experimental, raises an exception
test-warnings: no
strictness: veryhigh
max-line-length: 160
autodetect: yes
requirements:
    - dev-requirements.txt

python-targets:
  - 2
  - 3
ignore-paths:
  - examples/webchat
  - doc/
  - build
  - dist
  - .eggs
  # util creates lots of warnings. ideally they should be fixed,
  # but that code doesn't change often
  - util
  # likewise with scripts
  - scripts/
  # This file has invalid syntax for Python 3, which is how
  # landscape.io runs things
  - gevent/_util_py2.py
ignore-patterns:
  # disabled code
  - greentest/xtest_.*py
  # standard library code
  - ^greentest/2.*
  - ^greentest/3.*
  # benchmarks that aren't used/changed much
  - ^greentest/bench_.*py

pyroma:
  run: true

pyflakes:
  disable:
    # F821: undefined name; caught better by pylint, where it can be
    # controlled for the whole file/per-line
    - F821
