language: python
sudo: false
python:
    - 2.6
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
env:
    - LINT=true
    - LINT=false
install:
    # First install a newer pip so that it can use the wheel cache
    # (only needed until travis upgrades pip to 7.x; note that the 3.5
    # environment uses pip 7.1 by default)
    - travis_retry pip install -U pip wheel
    # Then start installing our deps. Note that use of --build-options / --global-options / --install-options
    # disables the cache.
    # Bug https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3
    # means that installing cython on cpython 3.5 cannot use the wheel cache, which
    # means that the LINT=true case is quite slow (2.5 minutes). If this takes very long to fix,
    # we might want to do some refactoring to move installation into the makefile or a script.
    - travis_retry pip install -U tox cython greenlet pep8 pyflakes "coverage>=4.0b3" coveralls
script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $LINT == true ]]; then python setup.py develop && make travis_test_linters; elif [[ $LINT == false && $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then python setup.py develop && make fulltoxtest; elif [[ $LINT == false ]]; then python setup.py develop && make fulltoxtest; fi
notifications:
  email: false
# cache: pip seems not to work if `install` is replaced (https://github.com/travis-ci/travis-ci/issues/3239)
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
