language: python
sudo: false
python:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=travis-lint
install:
    - travis_retry pip install tox
script:
    - tox
notifications:
  email: false
