language: python
python:
 - "2.6"
 - "2.7"
matrix:
 include:
    # work around travis not supporting 2.5
  - python: "2.6"
    env: PYTHON=python2.5
script:
 - if [[ $PYTHON == 'python2.5' ]]; then NWORKERS=4 PYTHON=python2.5 make travis_cpython_25; fi
 - if [[ $PYTHON != 'python2.5' ]]; then NWORKERS=4 PYTHON=python$TRAVIS_PYTHON_VERSION make travis_cpython; fi
notifications:
  email: false
