language: python
sudo: false
env:
    - TOXENV=travis-lint
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=pypy
    - TOXENV=py33
    - TOXENV=py34
install:
    - travis_retry pip install -U pip tox
    # We only have a few files to compile, so not compiling cython itself
    # makes the overall build much faster.
    - travis_retry pip install --install-option='--no-cython-compile' cython
script:
    # Try to use the site packages of cython we just installed
    - tox --sitepackages --develop
notifications:
  email: false
cache:
  directories:
    - $HOME/.cache/pip
